# Pandas Library
Pandas is the most popular library of python used for data analysis. To work with it, first import the library.(you can use alias for simplicity).

In [1]:
import pandas as pd

Two main concepts in pandas are:

1. DataFrame
2. Series <br>
We will create our own data using these as follows

**DataFrame** <br>
DataFrame is a table. It contains an array of entries. Each entry corresponds to row and coloumn. For example: 31 is a entry whose row=0, column = yes.

In [2]:
data = pd.DataFrame({'yes':[31,3],'no':[33,9]})
print(data)

   yes  no
0   31  33
1    3   9

As you can see, the table is automatically given index values which starts for 0. If you wish to use give specific values to index, do follows:

In [3]:
data = pd.DataFrame({'Bob':["I likes it","Bland"],
                     'Alice':["It was awful","I liked it"]},
                     index = ['Product A','Product B'])
print(data)

                  Bob         Alice
Product A  I likes it  It was awful
Product B       Bland    I liked it

**Series**<br> Series is a sequence of data values. If DataFrame is Table, series is a List.

In [4]:
data = pd.Series([1,2,3,4])
data

0    1
1    2
2    3
3    4
dtype: int64

Series is just a colum of DataFrame. So, you can assign a row lable using `index` parameter. However, a Series does not have a column name. It only has one name overall.

In [5]:
data = pd.Series([30,40,50],index=['Subject A','Subject B','Subject c'],name = 'Marks of a Student')
data

Subject A    30
Subject B    40
Subject c    50
Name: Marks of a Student, dtype: int64

### Reading data files
As of now, we have seen how to create our own data. But, most of the time, we won't be creating data by hand. Instead, we will be working with the already existing data. Data can be stored in any format.By far the most used is CSV files.<br>
CSV stands for Comma separeted values. When you open a CSV file, you will get to see the data values separated by commas and hence the name CSV.<br>
To read the data into DataFrame, we use `pd.read_csv()` function.

In [6]:
data = pd.read_csv("/kaggle/input/datasets/datascikhan/e-commerce-sales-and-customer-analytics/customer_master.csv")

Before we move further, let us know how to upload the datasets to kaggle and sue them:

1. **Add the dataset (if not already done)** <br>
In your notebook, look at the right-hand sidebar (in the Notebook editor). Click "Add Input" (sometimes shown as a "+" next to "Input"). Search for your dataset by name and click the + to add it. This mounts it — it doesn't copy files into your working code.
2. **Find the exact path** <br>
Once added, Kaggle places datasets under:<br>
`/kaggle/input/<dataset-folder-name>/`
3. To see the exact folder and file names (they don't always match what you expect), run this in a code cell:
```
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
```
Now use the path you get after running this code in the read_csv()

We can use the `shape` attribute to check how large the resulting DataFrame is:

In [7]:
data.shape

(25000, 11)

The above output tells us that the new DataFrame created have total of 25000 records split across 11 columns. <br>
To examine the content of the dataset, we can use `head()` command which gives us the first 5 rows of the dataset.

In [8]:
data.head()

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,61,Male,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,30,Male,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34

If you wish to fetch more than just 5 rows then specify the nymber of rows in the `head()` command.

In [9]:
data.head(10)

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,61,Male,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,30,Male,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34
5,CUST-000006,Alexander Gutierrez,72,Female,Consumer,Lake Rachelbury,Scotland,UK,North,75468,40.89
6,CUST-000007,Adriana Jennings,27,Female,Premium,East Joseph,New York,USA,East,35681,25.52
7,CUST-000008,Trevor Brown,40,Male,Consumer,Hillport,Illinois,USA,Central,63970,66.68
8,CUST-000009,Kirsten Ward,59,Male,Consumer,Lake Colleen,Michigan,USA,Central,78332,31.03
9,CUST-000010,Christina Ellis,35,Female,VIP,West Adam,Lower Saxony,Germany,North,52365,28.54

If you wish to checkout the data from last, then use `tail()` command. This command gives the last 5 rows of the dataset.

In [10]:
data.tail()

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
24995,CUST-024996,Nathan Porter,40,Male,Consumer,Kristineport,Texas,USA,South,62079,14.92
24996,CUST-024997,Heather Graham,19,Female,Consumer,Ruizside,North Rhine,Germany,West,16488,11.41
24997,CUST-024998,John Smith,31,Female,Business,Jacksonside,North Carolina,USA,South,86726,66.95
24998,CUST-024999,Eric Castillo,52,Female,Consumer,West Brandonfort,Ontario,Canada,East,92053,24.97
24999,CUST-025000,Peter Everett,52,Male,Premium,Blankenshipburgh,Ohio,USA,Central,73417,52.38

In [11]:
#to fetch the last 10 rows of the dataset
data.tail(10)

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
24990,CUST-024991,Larry Mejia,72,Male,Business,Lake George,Illinois,USA,Central,16836,9.61
24991,CUST-024992,Laura Blanchard,52,Female,Premium,Pierceshire,California,USA,West,17020,76.92
24992,CUST-024993,Jacob Cross,36,Male,Consumer,Port Roberthaven,Pennsylvania,USA,East,96558,27.17
24993,CUST-024994,Destiny Martinez,21,Female,Consumer,West Theresaport,North Rhine,Germany,West,86731,20.05
24994,CUST-024995,Michele Stuart,44,Male,Consumer,West Curtis,Pennsylvania,USA,East,75784,76.28
24995,CUST-024996,Nathan Porter,40,Male,Consumer,Kristineport,Texas,USA,South,62079,14.92
24996,CUST-024997,Heather Graham,19,Female,Consumer,Ruizside,North Rhine,Germany,West,16488,11.41
24997,CUST-024998,John Smith,31,Female,Business,Jacksonside,North Carolina,USA,South,86726,66.95
24998,CUST-024999,Eric Castillo,52,Female,Consumer,West Brandonfort,Ontario,Canada,East,92053,24.97
24999,CUST-025000,Peter Everett,52,Male,Premium,Blankenshipburgh,Ohio,USA,Central,73417,52.38

The `pd.read_csv()` has over 30 optional parameters. For example, you can see in this dataset taht the CSV file has a built-in index, which pandas did not pick up automatically. To make pandas use that column for the index (instead of creating a new one from scratch), we can specify an `index_col`.

In [12]:
data = pd.read_csv("/kaggle/input/datasets/datascikhan/e-commerce-sales-and-customer-analytics/customer_master.csv",index_col=0)
data.head()

,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
customer_id,,,,,,,,,,
CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
CUST-000002,Joseph James,61,Male,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
CUST-000004,David Lopez,30,Male,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34

Now, let us learn how to save a DataFarme as CSV to disk using `to_csv()`. Let us create a DataFrame called animals and save it as a CSV file to disk under the name `cows_and_goats.csv`.

In [13]:
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

        Cows  Goats
Year 1    12     22
Year 2    20     19

In [14]:
#use the function to_csv() to convert the datafame to csv
animals.to_csv("cows_and_goats.csv")

### Indexing, Selecting and Assigning

One of the most important thing to remember while working with data in python is how to go about selecting a particular data points relevant to you.

In python we can access the property of an object by accessing it as a attribute. Let us say that `student` is an object and you can access the roll no of this student by using `student.roll_no`. <br>
In the same way, you can access the columns of the DataFrame.<br>
Hence, to access the `customer_id` property of `data` we can use:

In [15]:
data = pd.read_csv("/kaggle/input/datasets/datascikhan/e-commerce-sales-and-customer-analytics/customer_master.csv")
data.customer_id

0        CUST-000001
1        CUST-000002
2        CUST-000003
3        CUST-000004
4        CUST-000005
            ...
24995    CUST-024996
24996    CUST-024997
24997    CUST-024998
24998    CUST-024999
24999    CUST-025000
Name: customer_id, Length: 25000, dtype: object

In [16]:
#to fetch only the 1st id
data.customer_id[0]

'CUST-000001'

We can aslo access the columns of the DataFrame the way we access the values of the dictionary.

In [17]:
data['customer_id']

0        CUST-000001
1        CUST-000002
2        CUST-000003
3        CUST-000004
4        CUST-000005
            ...
24995    CUST-024996
24996    CUST-024997
24997    CUST-024998
24998    CUST-024999
24999    CUST-025000
Name: customer_id, Length: 25000, dtype: object

These are the two ways of accessing the columns of the DataFrame. Both can be used but using dictionary would be better. <br>
The reason being, if the column name is `customer name`, then we cannot access it using `data.customer name`.

Each column of the DataFrame is nothing but a Series. Series looks kind of like dictionary. Hence, to get asingle specific values, you just need to use another indexing operator `[]`.

In [18]:
#gives the first element of the Series.
data['customer_id'][0]

'CUST-000001'

#### Indexing in pandas
Indexing operator and attribute selection is easy to pick up and use. But, pandas has it's own accessor operators,`loc` and `iloc`, which can be used for more advanced operations.<br>
pandas indexing has 2 paradigms:
1. Index-based selection
2. Label-based selection

**Index-based selection**
<br>Selecting the data based on it's position in the dataset.
<br>If you wish to get the first row of the DataFrame, do the following:

In [19]:
data.iloc[0]

customer_id                   CUST-000001
customer_name                Donna Miller
customer_age                           54
gender                             Female
customer_segment                 Consumer
customer_city                  Laurenland
customer_state                      Dubai
customer_country                      UAE
region                              South
customer_postal_code                11253
customer_acquisition_cost           13.58
Name: 0, dtype: object

`iloc` and `loc` are row first, column second. But this is opposite of when we used basic indexing operator, which is column first, row-second.<br>
This means that fetching rows is easier than fetching the columns.<br>
To get the first column, we do the following:

In [20]:
data.iloc[:,0]

0        CUST-000001
1        CUST-000002
2        CUST-000003
3        CUST-000004
4        CUST-000005
            ...
24995    CUST-024996
24996    CUST-024997
24997    CUST-024998
24998    CUST-024999
24999    CUST-025000
Name: customer_id, Length: 25000, dtype: object

`data.iloc[:,0]` fetches all the rows and 1st column. The common syntax would be `data.iloc[row,column]`.<br>
You can specify the range of rows and columns you wish to fetch. For example, you wish to fetch the first 10 rows and 1st 4 columns:

In [21]:
data.iloc[0:10,0:4]

   customer_id        customer_name  customer_age  gender
0  CUST-000001         Donna Miller            54  Female
1  CUST-000002         Joseph James            61    Male
2  CUST-000003         Daniel Smith            47    Male
3  CUST-000004          David Lopez            30    Male
4  CUST-000005         Dakota Davis            55  Female
5  CUST-000006  Alexander Gutierrez            72  Female
6  CUST-000007     Adriana Jennings            27  Female
7  CUST-000008         Trevor Brown            40    Male
8  CUST-000009         Kirsten Ward            59    Male
9  CUST-000010      Christina Ellis            35  Female

You can notice that though we want 10 rows and 4 columns, the element at the 10th index and 4th row is not retrieved. This is because the final range is not included but the initial range is included and the index starts from 0 for both row and column.

You can also pass list:

In [22]:
#here [0,1,3,6] represents the index of the rows
data.iloc[[0,1,3,6],0]

0    CUST-000001
1    CUST-000002
3    CUST-000004
6    CUST-000007
Name: customer_id, dtype: object

You can also use negative numbers to represent the ranges. It will start counting forward from the end ofthe values. <br>
To fetch the last 5 elements of the dataset:

In [23]:
data.iloc[-5:]

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
24995,CUST-024996,Nathan Porter,40,Male,Consumer,Kristineport,Texas,USA,South,62079,14.92
24996,CUST-024997,Heather Graham,19,Female,Consumer,Ruizside,North Rhine,Germany,West,16488,11.41
24997,CUST-024998,John Smith,31,Female,Business,Jacksonside,North Carolina,USA,South,86726,66.95
24998,CUST-024999,Eric Castillo,52,Female,Consumer,West Brandonfort,Ontario,Canada,East,92053,24.97
24999,CUST-025000,Peter Everett,52,Male,Premium,Blankenshipburgh,Ohio,USA,Central,73417,52.38

**Lable-based selection**<br>
Here we use the data index value as attribute, not the position. For this, we use `loc` operator.

In [24]:
#fetch the data present at the 0th row and the column named "customer_id".
data.loc[0,"customer_id"]

'CUST-000001'

In [25]:
data.loc[0:3,["customer_id","customer_name"]]

   customer_id customer_name
0  CUST-000001  Donna Miller
1  CUST-000002  Joseph James
2  CUST-000003  Daniel Smith
3  CUST-000004   David Lopez

Notice that you can use position for rows but not or columns. The other important thing is that the final range is also included in the result.

**Choosing between `iloc` and `loc`** <br>
You might have noticed that the way indexing works using `iloc` and `loc` is different. `iloc` uses the python's stdlib indexing, where the first elemnt is included and the last elemnt is excluded while mentioning the range.So, `0:10` will give entries `0,1,2...9` but the 10th entry is excluded.<br>
As for `loc`, 0:10 will give the entries `0,1,2,3...10`.Here, the last element is included.

#### Manipulating the index
We can change the name of the index using `set_index()` as follows:

In [26]:
data.set_index("customer_id")

,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
customer_id,,,,,,,,,,
CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
CUST-000002,Joseph James,61,Male,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
CUST-000004,David Lopez,30,Male,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34
...,...,...,...,...,...,...,...,...,...,...
CUST-024996,Nathan Porter,40,Male,Consumer,Kristineport,Texas,USA,South,62079,14.92
CUST-024997,Heather Graham,19,Female,Consumer,Ruizside,North Rhine,Germany,West,16488,11.41
CUST-024998,John Smith,31,Female,Business,Jacksonside,North Carolina,USA,South,86726,66.95
CUST-024999,Eric Castillo,52,Female,Consumer,West Brandonfort,Ontario,Canada,East,92053,24.97
CUST-025000,Peter Everett,52,Male,Premium,Blankenshipburgh,Ohio,USA,Central,73417,52.38

As you can see, you can set any column as an index using the given function. In the above example, we are using the `customer_id` as the index.

#### Conditional selection 
We can ask questions based on conditions. Let us say we want to knwo whether the `customer_acquisition_cost` is morethan 13 or not for each row:

In [27]:
data.customer_acquisition_cost >13

0         True
1         True
2         True
3         True
4         True
         ...
24995     True
24996    False
24997     True
24998     True
24999     True
Name: customer_acquisition_cost, Length: 25000, dtype: bool

As you can see, it returns True or False based on the condition we asked.Now, you can use this inside the `loc` operator to fetch the data which return True.

In [28]:
data.loc[data.customer_acquisition_cost>13]

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,61,Male,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,30,Male,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34
...,...,...,...,...,...,...,...,...,...,...,...
24994,CUST-024995,Michele Stuart,44,Male,Consumer,West Curtis,Pennsylvania,USA,East,75784,76.28
24995,CUST-024996,Nathan Porter,40,Male,Consumer,Kristineport,Texas,USA,South,62079,14.92
24997,CUST-024998,John Smith,31,Female,Business,Jacksonside,North Carolina,USA,South,86726,66.95
24998,CUST-024999,Eric Castillo,52,Female,Consumer,West Brandonfort,Ontario,Canada,East,92053,24.97
24999,CUST-025000,Peter Everett,52,Male,Premium,Blankenshipburgh,Ohio,USA,Central,73417,52.38

We can aslo use 2 different condtions at the same time. For example, retrieve the data where the customer is Female and the customer_acquisition_cost is greater than 20. For this use the `&` operator.

In [29]:
data.loc[(data.gender == "Female") & (data.customer_acquisition_cost > 20)]

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34
5,CUST-000006,Alexander Gutierrez,72,Female,Consumer,Lake Rachelbury,Scotland,UK,North,75468,40.89
6,CUST-000007,Adriana Jennings,27,Female,Premium,East Joseph,New York,USA,East,35681,25.52
9,CUST-000010,Christina Ellis,35,Female,VIP,West Adam,Lower Saxony,Germany,North,52365,28.54
10,CUST-000011,Martin Oliver,72,Female,VIP,Scottchester,Sharjah,UAE,North,85833,32.86
...,...,...,...,...,...,...,...,...,...,...,...
24988,CUST-024989,Stacy Chavez,29,Female,Consumer,Lake Wendyport,Illinois,USA,Central,74993,54.65
24991,CUST-024992,Laura Blanchard,52,Female,Premium,Pierceshire,California,USA,West,17020,76.92
24993,CUST-024994,Destiny Martinez,21,Female,Consumer,West Theresaport,North Rhine,Germany,West,86731,20.05
24997,CUST-024998,John Smith,31,Female,Business,Jacksonside,North Carolina,USA,South,86726,66.95
24998,CUST-024999,Eric Castillo,52,Female,Consumer,West Brandonfort,Ontario,Canada,East,92053,24.97

THe customer is Female or the customer_acquisition_cost is greater than 20. Here we use `|` operator.

In [30]:
data.loc[(data.gender =="Female") | (data.customer_acquisition_cost > 20)]

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,61,Male,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34
5,CUST-000006,Alexander Gutierrez,72,Female,Consumer,Lake Rachelbury,Scotland,UK,North,75468,40.89
...,...,...,...,...,...,...,...,...,...,...,...
24994,CUST-024995,Michele Stuart,44,Male,Consumer,West Curtis,Pennsylvania,USA,East,75784,76.28
24996,CUST-024997,Heather Graham,19,Female,Consumer,Ruizside,North Rhine,Germany,West,16488,11.41
24997,CUST-024998,John Smith,31,Female,Business,Jacksonside,North Carolina,USA,South,86726,66.95
24998,CUST-024999,Eric Castillo,52,Female,Consumer,West Brandonfort,Ontario,Canada,East,92053,24.97
24999,CUST-025000,Peter Everett,52,Male,Premium,Blankenshipburgh,Ohio,USA,Central,73417,52.38

Pandas comes with a few built-in conditional selectors, here we will mainly deal with 2.
1. `isin()`
2. `isnull()`

`isin()` lets you select data whose value 'is in' a list of values.For example, display only those elements where the customer is either from USA or Canada.

In [31]:
data.loc[data.customer_country.isin(["USA","Canada"])]

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
3,CUST-000004,David Lopez,30,Male,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34
6,CUST-000007,Adriana Jennings,27,Female,Premium,East Joseph,New York,USA,East,35681,25.52
7,CUST-000008,Trevor Brown,40,Male,Consumer,Hillport,Illinois,USA,Central,63970,66.68
8,CUST-000009,Kirsten Ward,59,Male,Consumer,Lake Colleen,Michigan,USA,Central,78332,31.03
...,...,...,...,...,...,...,...,...,...,...,...
24994,CUST-024995,Michele Stuart,44,Male,Consumer,West Curtis,Pennsylvania,USA,East,75784,76.28
24995,CUST-024996,Nathan Porter,40,Male,Consumer,Kristineport,Texas,USA,South,62079,14.92
24997,CUST-024998,John Smith,31,Female,Business,Jacksonside,North Carolina,USA,South,86726,66.95
24998,CUST-024999,Eric Castillo,52,Female,Consumer,West Brandonfort,Ontario,Canada,East,92053,24.97
24999,CUST-025000,Peter Everett,52,Male,Premium,Blankenshipburgh,Ohio,USA,Central,73417,52.38

`isnull()` and it's comanion `notnull()`. These are used to retrieve any values which are null(not  ull) empty(NaN). For example, display the data where the age of cutsomer is given.

In [32]:
data.loc[data.customer_age.notnull()]

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,61,Male,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,30,Male,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34
...,...,...,...,...,...,...,...,...,...,...,...
24995,CUST-024996,Nathan Porter,40,Male,Consumer,Kristineport,Texas,USA,South,62079,14.92
24996,CUST-024997,Heather Graham,19,Female,Consumer,Ruizside,North Rhine,Germany,West,16488,11.41
24997,CUST-024998,John Smith,31,Female,Business,Jacksonside,North Carolina,USA,South,86726,66.95
24998,CUST-024999,Eric Castillo,52,Female,Consumer,West Brandonfort,Ontario,Canada,East,92053,24.97
24999,CUST-025000,Peter Everett,52,Male,Premium,Blankenshipburgh,Ohio,USA,Central,73417,52.38

*Note*<br>
The dataset used here is a clean dataset.Hence, use the dataset with null values in it, if you wish to check the presence of the null.

#### Assigning the data
You can either assign a constant value or with an iterable of values.

In [33]:
data["gender"] = "Female"
data.head(20)

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,61,Female,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,47,Female,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,30,Female,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34
5,CUST-000006,Alexander Gutierrez,72,Female,Consumer,Lake Rachelbury,Scotland,UK,North,75468,40.89
6,CUST-000007,Adriana Jennings,27,Female,Premium,East Joseph,New York,USA,East,35681,25.52
7,CUST-000008,Trevor Brown,40,Female,Consumer,Hillport,Illinois,USA,Central,63970,66.68
8,CUST-000009,Kirsten Ward,59,Female,Consumer,Lake Colleen,Michigan,USA,Central,78332,31.03
9,CUST-000010,Christina Ellis,35,Female,VIP,West Adam,Lower Saxony,Germany,North,52365,28.54
10,CUST-000011,Martin Oliver,72,Female,VIP,Scottchester,Sharjah,UAE,North,85833,32.86
11,CUST-000012,Terri Taylor,44,Female,Premium,Carrieborough,Illinois,USA,Central,63285,46.97
12,CUST-000013,Leon Oconnell,55,Female,VIP,Kellyfort,North Carolina,USA,South,75982,35.51
13,CUST-000014,Kimberly Nguyen,72,Female,Consumer,Lisafurt,Pennsylvania,USA,East,48344,72.75
14,CUST-000015,Daniel Elliott,62,Female,Premium,Lake Katrina,Illinois,USA,Central,4028,48.45
15,CUST-000016,Stephanie Murray,43,Female,Business,South Lauren,North Carolina,USA,South,91312,74.92
16,CUST-000017,Chad Abbott,30,Female,Premium,Chambersberg,New York,USA,East,83513,18.90
17,CUST-000018,Kevin King,47,Female,Consumer,Lake Rodney,North Carolina,USA,South,49913,72.74
18,CUST-000019,Charles Ewing,49,Female,Premium,Aguilarside,Maharashtra,India,West,66903,15.73
19,CUST-000020,Sandra Kane,31,Female,VIP,Stephensstad,Karnataka,India,South,92465,30.31

As you can see, each value of the given attribute is changed to a constant value, which is Female.

In [34]:
data["customer_age"] = [len(data) - i for i in range(len(data))]
data.head()

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,25000,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,24999,Female,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,24998,Female,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,24997,Female,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,24996,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34

If you wish to change only few rows, then slice the dataset and use them or create a new DataFrame and use. <br>
*Note*:<br>
When using `head()`, remember that it gives the view of the original dataset and not the independent one.So, first create a copy, if you are trying to assign the values.

In [35]:
data2 = data.head(10).copy()
data2.customer_age = range(10,0,-1)
data2

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,10,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,9,Female,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,8,Female,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,7,Female,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,6,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34
5,CUST-000006,Alexander Gutierrez,5,Female,Consumer,Lake Rachelbury,Scotland,UK,North,75468,40.89
6,CUST-000007,Adriana Jennings,4,Female,Premium,East Joseph,New York,USA,East,35681,25.52
7,CUST-000008,Trevor Brown,3,Female,Consumer,Hillport,Illinois,USA,Central,63970,66.68
8,CUST-000009,Kirsten Ward,2,Female,Consumer,Lake Colleen,Michigan,USA,Central,78332,31.03
9,CUST-000010,Christina Ellis,1,Female,VIP,West Adam,Lower Saxony,Germany,North,52365,28.54

### Summary Functions and Maps
<br>
We have seen how to select relevant data out of DataFrame and Series. But the data will not always be in the form we need. We will have to do some extra work to rereformat the data. This section will cover few operations which we can use to get the data in the right format.

##### Summary Functions
Pandas have some summary fucntions which will restructure the data in a useful way. For example, conside the `describe()` method.

In [36]:
data.customer_name.describe()

count          25000
unique         21631
top       John Smith
freq              17
Name: customer_name, dtype: object

`describe()` gives us high level summary of the mentioned column. Here, it gave us the summary of the column '`customer_name`. The output changes based on the datatype of the column used.

In [37]:
data.customer_age.describe()

count    25000.000000
mean     12500.500000
std       7217.022701
min          1.000000
25%       6250.750000
50%      12500.500000
75%      18750.250000
max      25000.000000
Name: customer_age, dtype: float64

To calculate the average age of all customers: use `mean()`.

In [38]:
data.customer_age.mean()

np.float64(12500.5)

To get a list of unique values of the column, use `unique()`.

In [39]:
data.gender.unique()

array(['Female'], dtype=object)

To get list of unique values *and* how often they occur in dataset, use `value_counts()`.

In [40]:
data.gender.value_counts()

gender
Female    25000
Name: count, dtype: int64

##### Maps
In data science, we often need to transform the data present in one form to another, or creating new representations from the existing data. For these, we use `maps`.  There are 2 maping methods. Let us use `map()` first.

In [41]:
data1 = data.customer_age.mean()
data.customer_age.map(lambda x: x-data1)

0        12499.5
1        12498.5
2        12497.5
3        12496.5
4        12495.5
          ...
24995   -12495.5
24996   -12496.5
24997   -12497.5
24998   -12498.5
24999   -12499.5
Name: customer_age, Length: 25000, dtype: float64

The function you pass to `map()` should expect a single value from the Series (a point value, in the above example), and return a transformed version of that value. `map()` returns a new Series where all the values have been transformed by your function.

`apply()` is another equivalent method. It is used to change the whole DataFrame by calling a custom method on each rows.

In [42]:
def change(row):
    row.customer_age = row.customer_age - data1
    return row

data.apply(change, axis="columns")

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,12499.5,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,12498.5,Female,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,12497.5,Female,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,12496.5,Female,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,12495.5,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34
...,...,...,...,...,...,...,...,...,...,...,...
24995,CUST-024996,Nathan Porter,-12495.5,Female,Consumer,Kristineport,Texas,USA,South,62079,14.92
24996,CUST-024997,Heather Graham,-12496.5,Female,Consumer,Ruizside,North Rhine,Germany,West,16488,11.41
24997,CUST-024998,John Smith,-12497.5,Female,Business,Jacksonside,North Carolina,USA,South,86726,66.95
24998,CUST-024999,Eric Castillo,-12498.5,Female,Consumer,West Brandonfort,Ontario,Canada,East,92053,24.97
24999,CUST-025000,Peter Everett,-12499.5,Female,Premium,Blankenshipburgh,Ohio,USA,Central,73417,52.38

If we had called `apply()` with `axis='index'`, then instead of passing a function to transform each row, we would need to give a function to transform each column.

Note that `map()` and `apply()` return new, transformed Series and DataFrames, respectively. They don't modify the original data they're called on.

Pandas provides many common iperations as built-ins.

In [43]:
data_mean = data.customer_age.mean()
data.customer_age - data_mean

0        12499.5
1        12498.5
2        12497.5
3        12496.5
4        12495.5
          ...
24995   -12495.5
24996   -12496.5
24997   -12497.5
24998   -12498.5
24999   -12499.5
Name: customer_age, Length: 25000, dtype: float64

Pandas will also undestand what to do if we perform these operations between series of equal length.

In [44]:
data.customer_city + ' - ' + data.customer_state

0                  Laurenland - Dubai
1           Lake Peter - Lower Saxony
2              Seanview - North Rhine
3         Hawkinshaven - Pennsylvania
4            New Carlymouth - Florida
                     ...
24995            Kristineport - Texas
24996          Ruizside - North Rhine
24997    Jacksonside - North Carolina
24998      West Brandonfort - Ontario
24999         Blankenshipburgh - Ohio
Length: 25000, dtype: object

### Grouping and Sorting

We have used map till now to change the data in the DataFrame or Series one at a time for entire column. Sometimes, we want to group the data and perform some operations. We will do it using `groupby()` as follws:

In [45]:
data.groupby("customer_age").gender.value_counts()

customer_age  gender
1             Female    1
2             Female    1
3             Female    1
4             Female    1
5             Female    1
                       ..
24996         Female    1
24997         Female    1
24998         Female    1
24999         Female    1
25000         Female    1
Name: count, Length: 25000, dtype: int64

We grouped the customers based on their age and then for each group, we are finding the unique list of gender and counts.

You can think of each group as a slice of the DataFrame and then you can access them using `apply()`.

In [46]:
data.groupby('customer_age').apply(lambda df: df.customer_age)

/tmp/ipykernel_16/7430044.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  data.groupby('customer_age').apply(lambda df: df.customer_age)

customer_age
1             24999        1
2             24998        2
3             24997        3
4             24996        4
5             24995        5
                       ...
24996         4        24996
24997         3        24997
24998         2        24998
24999         1        24999
25000         0        25000
Name: customer_age, Length: 25000, dtype: int64

In [47]:
data.groupby(['customer_country','region']).head()

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,25000,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,24999,Female,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,24998,Female,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,24997,Female,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,24996,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34
...,...,...,...,...,...,...,...,...,...,...,...
478,CUST-000479,Kim Mitchell,24522,Female,Consumer,South Kelly,New South Wales,Australia,East,7650,67.48
489,CUST-000490,Nicole Young,24511,Female,Consumer,Chavezmouth,Queensland,Australia,North,10908,21.77
511,CUST-000512,Catherine Lopez,24489,Female,VIP,Port Kimberlyport,British Columbia,Canada,West,92941,35.51
524,CUST-000525,Larry Mcclain,24476,Female,Premium,Williamstown,New South Wales,Australia,East,62201,36.42
601,CUST-000602,Lori Davis,24399,Female,Consumer,Port Brittany,British Columbia,Canada,West,14438,78.11

Another `groupby()` method worth mentioning is `agg()` which lets us run a bunch of different functions on the DataFrame simultaneously. For example, we can generate a simple summer of the dataset.

In [48]:
data.groupby('customer_country').agg([len])

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,region,customer_postal_code,customer_acquisition_cost
,len,len,len,len,len,len,len,len,len,len
customer_country,,,,,,,,,,
Australia,1233,1233,1233,1233,1233,1233,1233,1233,1233,1233
Canada,1279,1279,1279,1279,1279,1279,1279,1279,1279,1279
Germany,2046,2046,2046,2046,2046,2046,2046,2046,2046,2046
India,1041,1041,1041,1041,1041,1041,1041,1041,1041,1041
UAE,775,775,775,775,775,775,775,775,775,775
UK,3701,3701,3701,3701,3701,3701,3701,3701,3701,3701
USA,14925,14925,14925,14925,14925,14925,14925,14925,14925,14925

#### Mulit-indexing
Generally, we have only one-level of indexing by default.Using multi-indexing you can lable a row by different names at the same time.

In [49]:
multi_index_data = pd.DataFrame({"Sales":[10,20,30,40]},
                            pd.MultiIndex.from_tuples([
                                ("out1","in1"),
                                ("out1","in2"),
                                ("out2","in3"),
                                ("out2","in4")
                            ])   )

multi_index_data

          Sales
out1 in1     10
     in2     20
out2 in3     30
     in4     40

In [50]:
data.groupby(["customer_id","customer_name"]).customer_segment.agg([len])

                            len
customer_id customer_name
CUST-000001 Donna Miller      1
CUST-000002 Joseph James      1
CUST-000003 Daniel Smith      1
CUST-000004 David Lopez       1
CUST-000005 Dakota Davis      1
...                         ...
CUST-024996 Nathan Porter     1
CUST-024997 Heather Graham    1
CUST-024998 John Smith        1
CUST-024999 Eric Castillo     1
CUST-025000 Peter Everett     1

[25000 rows x 1 columns]

You can also reset the index from multi-level to single level using `reset_index()`.

In [51]:
multi_index_data.reset_index()

  level_0 level_1  Sales
0    out1     in1     10
1    out1     in2     20
2    out2     in3     30
3    out2     in4     40

#### Sorting
You can sort the values of the dataset using `sort_values(by= )` method.

In [52]:
data.sort_values(by = "customer_age")

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
24999,CUST-025000,Peter Everett,1,Female,Premium,Blankenshipburgh,Ohio,USA,Central,73417,52.38
24998,CUST-024999,Eric Castillo,2,Female,Consumer,West Brandonfort,Ontario,Canada,East,92053,24.97
24997,CUST-024998,John Smith,3,Female,Business,Jacksonside,North Carolina,USA,South,86726,66.95
24996,CUST-024997,Heather Graham,4,Female,Consumer,Ruizside,North Rhine,Germany,West,16488,11.41
24995,CUST-024996,Nathan Porter,5,Female,Consumer,Kristineport,Texas,USA,South,62079,14.92
...,...,...,...,...,...,...,...,...,...,...,...
4,CUST-000005,Dakota Davis,24996,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34
3,CUST-000004,David Lopez,24997,Female,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
2,CUST-000003,Daniel Smith,24998,Female,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
1,CUST-000002,Joseph James,24999,Female,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
0,CUST-000001,Donna Miller,25000,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58

By default, it sorts in ascending order. To sort in descending values, do the following:

In [53]:
data.sort_values(by="customer_id",ascending=False)

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
24999,CUST-025000,Peter Everett,1,Female,Premium,Blankenshipburgh,Ohio,USA,Central,73417,52.38
24998,CUST-024999,Eric Castillo,2,Female,Consumer,West Brandonfort,Ontario,Canada,East,92053,24.97
24997,CUST-024998,John Smith,3,Female,Business,Jacksonside,North Carolina,USA,South,86726,66.95
24996,CUST-024997,Heather Graham,4,Female,Consumer,Ruizside,North Rhine,Germany,West,16488,11.41
24995,CUST-024996,Nathan Porter,5,Female,Consumer,Kristineport,Texas,USA,South,62079,14.92
...,...,...,...,...,...,...,...,...,...,...,...
4,CUST-000005,Dakota Davis,24996,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34
3,CUST-000004,David Lopez,24997,Female,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
2,CUST-000003,Daniel Smith,24998,Female,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
1,CUST-000002,Joseph James,24999,Female,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
0,CUST-000001,Donna Miller,25000,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58

To sort by index values, use `sort_index()`

In [54]:
data.sort_index()

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,25000,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,24999,Female,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,24998,Female,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,24997,Female,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,24996,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34
...,...,...,...,...,...,...,...,...,...,...,...
24995,CUST-024996,Nathan Porter,5,Female,Consumer,Kristineport,Texas,USA,South,62079,14.92
24996,CUST-024997,Heather Graham,4,Female,Consumer,Ruizside,North Rhine,Germany,West,16488,11.41
24997,CUST-024998,John Smith,3,Female,Business,Jacksonside,North Carolina,USA,South,86726,66.95
24998,CUST-024999,Eric Castillo,2,Female,Consumer,West Brandonfort,Ontario,Canada,East,92053,24.97
24999,CUST-025000,Peter Everett,1,Female,Premium,Blankenshipburgh,Ohio,USA,Central,73417,52.38

Finally, know that you can sort using multiple values.

In [55]:
data.sort_values(["customer_age","region"])

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
24999,CUST-025000,Peter Everett,1,Female,Premium,Blankenshipburgh,Ohio,USA,Central,73417,52.38
24998,CUST-024999,Eric Castillo,2,Female,Consumer,West Brandonfort,Ontario,Canada,East,92053,24.97
24997,CUST-024998,John Smith,3,Female,Business,Jacksonside,North Carolina,USA,South,86726,66.95
24996,CUST-024997,Heather Graham,4,Female,Consumer,Ruizside,North Rhine,Germany,West,16488,11.41
24995,CUST-024996,Nathan Porter,5,Female,Consumer,Kristineport,Texas,USA,South,62079,14.92
...,...,...,...,...,...,...,...,...,...,...,...
4,CUST-000005,Dakota Davis,24996,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34
3,CUST-000004,David Lopez,24997,Female,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
2,CUST-000003,Daniel Smith,24998,Female,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
1,CUST-000002,Joseph James,24999,Female,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
0,CUST-000001,Donna Miller,25000,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58

Way to get the count of customers in a particular group.

In [56]:
data.groupby("customer_age").size()

customer_age
1        1
2        1
3        1
4        1
5        1
        ..
24996    1
24997    1
24998    1
24999    1
25000    1
Length: 25000, dtype: int64

### Data Types and Missing values

`dtype` is used to get the data type of the specific column.

In [57]:
data.head()

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,25000,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,24999,Female,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,24998,Female,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,24997,Female,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,24996,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34

In [58]:
data.customer_age.dtype

dtype('int64')

Alternatively, `dtypes` will give the datatype of each column of the dataset.

In [59]:
data.dtypes

customer_id                   object
customer_name                 object
customer_age                   int64
gender                        object
customer_segment              object
customer_city                 object
customer_state                object
customer_country              object
region                        object
customer_postal_code           int64
customer_acquisition_cost    float64
dtype: object

One peculiarity to keep in mind is that columns consisting entirely of strings do not get their own type; they are instead given the `object` type.

It is possible to chnage the datatype of the column wherevr such convertions makes sense by uisng `astype()`.

In [60]:
data.customer_acquisition_cost.astype('int64')

0        13
1        27
2        31
3        16
4        41
         ..
24995    14
24996    11
24997    66
24998    24
24999    52
Name: customer_acquisition_cost, Length: 25000, dtype: int64

A DataFrame or Series index has it's own data type.

In [61]:
data.index.dtype

dtype('int64')

#### Missing Data
Entries missing values is given the value `NaN`, short for `not a number`. For technical reasons, the data type of `NaN` is `float64`.<br>
Pandas provides methods to check for the presence of `NaN` in the column of the dataset. You can use `isnull()` to fetch the NaN values.

In [62]:
data[pd.isnull(data.customer_age)]

Empty DataFrame
Columns: [customer_id, customer_name, customer_age, gender, customer_segment, customer_city, customer_state, customer_country, region, customer_postal_code, customer_acquisition_cost]
Index: []

Similarly, you can use `notnull()` to fetch all the present values.

In [63]:
data[pd.notnull(data.customer_age)]

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,25000,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,24999,Female,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,24998,Female,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,24997,Female,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,24996,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34
...,...,...,...,...,...,...,...,...,...,...,...
24995,CUST-024996,Nathan Porter,5,Female,Consumer,Kristineport,Texas,USA,South,62079,14.92
24996,CUST-024997,Heather Graham,4,Female,Consumer,Ruizside,North Rhine,Germany,West,16488,11.41
24997,CUST-024998,John Smith,3,Female,Business,Jacksonside,North Carolina,USA,South,86726,66.95
24998,CUST-024999,Eric Castillo,2,Female,Consumer,West Brandonfort,Ontario,Canada,East,92053,24.97
24999,CUST-025000,Peter Everett,1,Female,Premium,Blankenshipburgh,Ohio,USA,Central,73417,52.38

You can also replace the null values with anything using `fillna()`.

In [64]:
data.customer_age.fillna("Unknown")

0        25000
1        24999
2        24998
3        24997
4        24996
         ...
24995        5
24996        4
24997        3
24998        2
24999        1
Name: customer_age, Length: 25000, dtype: int64

Alternatively, we can replace the present non null value with any other value using `replace()` method.

In [65]:
data.gender.replace("Male","Female")

0        Female
1        Female
2        Female
3        Female
4        Female
          ...
24995    Female
24996    Female
24997    Female
24998    Female
24999    Female
Name: gender, Length: 25000, dtype: object

### Renaming and Combining