In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("/kaggle/input/datasets/datascikhan/e-commerce-sales-and-customer-analytics/customer_master.csv")

In [3]:
data.head()

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,61,Male,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,30,Male,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34

### Indexing, Selecting and Assigning

One of the most important thing to remember while working with data in python is how to go about selecting a particular data points relevant to you.

In python we can access the property of an object by accessing it as a attribute. Let us say that `student` is an object and you can access the roll no of this student by using `student.roll_no`. <br>
In the same way, you can access the columns of the DataFrame.<br>
Hence, to access the `customer_id` property of `dat` we can use:

In [4]:
data.customer_id

0        CUST-000001
1        CUST-000002
2        CUST-000003
3        CUST-000004
4        CUST-000005
            ...
24995    CUST-024996
24996    CUST-024997
24997    CUST-024998
24998    CUST-024999
24999    CUST-025000
Name: customer_id, Length: 25000, dtype: object

In [5]:
#to fetch only the 1st id
data.customer_id[0]

'CUST-000001'

We can aslo access the columns of the DataFrame the way we access the values of the dictionary.

In [6]:
data['customer_id']

0        CUST-000001
1        CUST-000002
2        CUST-000003
3        CUST-000004
4        CUST-000005
            ...
24995    CUST-024996
24996    CUST-024997
24997    CUST-024998
24998    CUST-024999
24999    CUST-025000
Name: customer_id, Length: 25000, dtype: object

These are the two ways of accessing the columns of the DataFrame. Both can be used but using dictionary would be better. <br>
The reason being, if the column name is `customer name`, then we cannot access it using `data.customer name`.

Each column of the DataFrame is nothing but a Series. Series looks kind of like dictionary. Hence, to get asingle specific values, you just need to use another indexing operator `[]`.

In [7]:
#gives the first element of the Series.
data['customer_id'][0]

'CUST-000001'

#### Indexing in pandas
Indexing operator and attribute selection is easy to pick up and use. But, pandas has it's own accessor operators,`loc` and `iloc`, which can be used for more advanced operations.<br>
pandas indexing has 2 paradigms:
1. Index-based selection
2. Label-based selection

**Index-based selection**
<br>Selecting the data based on it's position in the dataset.
<br>If you wish to get the first row of the DataFrame, do the following:

In [8]:
data.iloc[0]

customer_id                   CUST-000001
customer_name                Donna Miller
customer_age                           54
gender                             Female
customer_segment                 Consumer
customer_city                  Laurenland
customer_state                      Dubai
customer_country                      UAE
region                              South
customer_postal_code                11253
customer_acquisition_cost           13.58
Name: 0, dtype: object

`iloc` and `loc` are row first, column second. But this is opposite of when we used basic indexing operator, which is column first, row-second.<br>
This means that fetching rows is easier than fetching the columns.<br>
To get the first column, we do the following:

In [9]:
data.iloc[:,0]

0        CUST-000001
1        CUST-000002
2        CUST-000003
3        CUST-000004
4        CUST-000005
            ...
24995    CUST-024996
24996    CUST-024997
24997    CUST-024998
24998    CUST-024999
24999    CUST-025000
Name: customer_id, Length: 25000, dtype: object

`data.iloc[:,0]` fetches all the rows and 1st column. The common syntax would be `data.iloc[row,column]`.<br>
You can specify the range of rows and columns you wish to fetch. For example, you wish to fetch the first 10 rows and 1st 4 columns:

In [10]:
data.iloc[0:10,0:4]

   customer_id        customer_name  customer_age  gender
0  CUST-000001         Donna Miller            54  Female
1  CUST-000002         Joseph James            61    Male
2  CUST-000003         Daniel Smith            47    Male
3  CUST-000004          David Lopez            30    Male
4  CUST-000005         Dakota Davis            55  Female
5  CUST-000006  Alexander Gutierrez            72  Female
6  CUST-000007     Adriana Jennings            27  Female
7  CUST-000008         Trevor Brown            40    Male
8  CUST-000009         Kirsten Ward            59    Male
9  CUST-000010      Christina Ellis            35  Female

You can notice that though we want 10 rows and 4 columns, the element at the 10th index and 4th row is not retrieved. This is because the final range is not included but the initial range is included and the index starts from 0 for both row and column.

You can aslo pass list:

In [11]:
#here [0,1,3,6] represents the index of the rows
data.iloc[[0,1,3,6],0]

0    CUST-000001
1    CUST-000002
3    CUST-000004
6    CUST-000007
Name: customer_id, dtype: object

You can also use negative numbers to represent the ranges. IT will start counting forward from the end ofthe values. <br>
To fetch the last 5 elements of the dataset:

In [12]:
data.iloc[-5:]

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
24995,CUST-024996,Nathan Porter,40,Male,Consumer,Kristineport,Texas,USA,South,62079,14.92
24996,CUST-024997,Heather Graham,19,Female,Consumer,Ruizside,North Rhine,Germany,West,16488,11.41
24997,CUST-024998,John Smith,31,Female,Business,Jacksonside,North Carolina,USA,South,86726,66.95
24998,CUST-024999,Eric Castillo,52,Female,Consumer,West Brandonfort,Ontario,Canada,East,92053,24.97
24999,CUST-025000,Peter Everett,52,Male,Premium,Blankenshipburgh,Ohio,USA,Central,73417,52.38

**Lable-based selection**<br>
Here we use the data index value as attribute, not the position. For this, we use `loc` operator.

In [13]:
#fetch the data present at the 0th row and the column named "customer_id".
data.loc[0,"customer_id"]

'CUST-000001'

In [14]:
data.loc[0:3,["customer_id","customer_name"]]

   customer_id customer_name
0  CUST-000001  Donna Miller
1  CUST-000002  Joseph James
2  CUST-000003  Daniel Smith
3  CUST-000004   David Lopez

Notice that you can use position for rows but not or columns. The other important thing is that the final range is also included in the result.

**Choosing between `iloc` and `loc`** <br>
You might have noticed that the way indexing works using `iloc` and `loc` is different. `iloc` uses the python's stdlib indexing, where the first elemnt is included and the last elemnt is excluded while mentioning the range.So, `0:10` will give entries `0,1,2...9` but the 10th entry is excluded.<br>
As for `loc`, 0:10 will give the entries `0,1,2,3...10`.Here, the last element is included.

#### Manipulating the index
We can change the name of the index using `set_index()` as follows:

In [15]:
data.set_index("customer_id")

,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
customer_id,,,,,,,,,,
CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
CUST-000002,Joseph James,61,Male,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
CUST-000004,David Lopez,30,Male,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34
...,...,...,...,...,...,...,...,...,...,...
CUST-024996,Nathan Porter,40,Male,Consumer,Kristineport,Texas,USA,South,62079,14.92
CUST-024997,Heather Graham,19,Female,Consumer,Ruizside,North Rhine,Germany,West,16488,11.41
CUST-024998,John Smith,31,Female,Business,Jacksonside,North Carolina,USA,South,86726,66.95
CUST-024999,Eric Castillo,52,Female,Consumer,West Brandonfort,Ontario,Canada,East,92053,24.97
CUST-025000,Peter Everett,52,Male,Premium,Blankenshipburgh,Ohio,USA,Central,73417,52.38

As you can see, you can set any column as an index using the given function. In the above example, we are using the `customer_id` as the index.

#### Conditional selection 
We can ask questions based on conditions. Let us say we want to knwo whether the `customer_acquisition_cost` is morethan 13 or not for each row:

In [16]:
data.customer_acquisition_cost >13

0         True
1         True
2         True
3         True
4         True
         ...
24995     True
24996    False
24997     True
24998     True
24999     True
Name: customer_acquisition_cost, Length: 25000, dtype: bool

As you can see, it returns True or False based on the condition we asked.Now, you can use this inside the `loc` operator to fetch the data which return True.

In [17]:
data.loc[data.customer_acquisition_cost>13]

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,61,Male,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,30,Male,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34
...,...,...,...,...,...,...,...,...,...,...,...
24994,CUST-024995,Michele Stuart,44,Male,Consumer,West Curtis,Pennsylvania,USA,East,75784,76.28
24995,CUST-024996,Nathan Porter,40,Male,Consumer,Kristineport,Texas,USA,South,62079,14.92
24997,CUST-024998,John Smith,31,Female,Business,Jacksonside,North Carolina,USA,South,86726,66.95
24998,CUST-024999,Eric Castillo,52,Female,Consumer,West Brandonfort,Ontario,Canada,East,92053,24.97
24999,CUST-025000,Peter Everett,52,Male,Premium,Blankenshipburgh,Ohio,USA,Central,73417,52.38

We can aslo use 2 different condtions at the same time. For example, retrieve the data where the customer is Female and the customer_acquisition_cost is greater than 20. For this use the `&` operator.

In [18]:
data.loc[(data.gender == "Female") & (data.customer_acquisition_cost > 20)]

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34
5,CUST-000006,Alexander Gutierrez,72,Female,Consumer,Lake Rachelbury,Scotland,UK,North,75468,40.89
6,CUST-000007,Adriana Jennings,27,Female,Premium,East Joseph,New York,USA,East,35681,25.52
9,CUST-000010,Christina Ellis,35,Female,VIP,West Adam,Lower Saxony,Germany,North,52365,28.54
10,CUST-000011,Martin Oliver,72,Female,VIP,Scottchester,Sharjah,UAE,North,85833,32.86
...,...,...,...,...,...,...,...,...,...,...,...
24988,CUST-024989,Stacy Chavez,29,Female,Consumer,Lake Wendyport,Illinois,USA,Central,74993,54.65
24991,CUST-024992,Laura Blanchard,52,Female,Premium,Pierceshire,California,USA,West,17020,76.92
24993,CUST-024994,Destiny Martinez,21,Female,Consumer,West Theresaport,North Rhine,Germany,West,86731,20.05
24997,CUST-024998,John Smith,31,Female,Business,Jacksonside,North Carolina,USA,South,86726,66.95
24998,CUST-024999,Eric Castillo,52,Female,Consumer,West Brandonfort,Ontario,Canada,East,92053,24.97

THe customer is Female or the customer_acquisition_cost is greater than 20. Here we use `|` operator.

In [19]:
data.loc[(data.gender =="Female") | (data.customer_acquisition_cost > 20)]

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,61,Male,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34
5,CUST-000006,Alexander Gutierrez,72,Female,Consumer,Lake Rachelbury,Scotland,UK,North,75468,40.89
...,...,...,...,...,...,...,...,...,...,...,...
24994,CUST-024995,Michele Stuart,44,Male,Consumer,West Curtis,Pennsylvania,USA,East,75784,76.28
24996,CUST-024997,Heather Graham,19,Female,Consumer,Ruizside,North Rhine,Germany,West,16488,11.41
24997,CUST-024998,John Smith,31,Female,Business,Jacksonside,North Carolina,USA,South,86726,66.95
24998,CUST-024999,Eric Castillo,52,Female,Consumer,West Brandonfort,Ontario,Canada,East,92053,24.97
24999,CUST-025000,Peter Everett,52,Male,Premium,Blankenshipburgh,Ohio,USA,Central,73417,52.38